# Generated by Django 5.2.3 on 2025-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measurements',
        ),
        migrations.AddField(
            model_name='sensor',
            name='measurements',
            field=models.ManyToManyField(related_name='sensors', to='measurement.measurement'),
        ),
    ]
